# Interferometric Coherence and Closure Phase per ISMN Station

<br>

For each ISMN station, reads the per-acquisition GSLC window chips saved by
[`01b_get_nisar_gslc_windows.ipynb`](01b_get_nisar_gslc_windows.ipynb) and
computes, over a small window centered on the station's pixel:

- **pairwise coherence** for every pair of acquisitions from the same track
- **closure phase** for every triplet 

One CSV per station for each, under `nisar_data/<AOI>_GSLC_coherence_closure/`.
Purely local, in-memory -- no network access.

:::{note} Method
Implemented by `process_station()` in
[`util/nisar_coherence_closure.py`](../util/nisar_coherence_closure.py) --
see that module's docstrings for the coherence/closure-phase formulas and
the full column list. No triplet is dropped for low coherence; each carries
`min_coherence_HH`/`min_coherence_HV` so low-coherence triplets can be
filtered downstream without recomputing anything. Both CSVs are fully
rebuilt from scratch on every run.
:::

<hr>

## Overview

1. Load station list
2. Process each station: group by track, compute pairwise coherence and
   triplet closure phase, save CSVs
3. (Optional) Preview one station's output

<hr>

In [1]:
import sys
import os
import json
from pathlib import Path

from util.nisar_coherence_closure import process_station

C:\Users\geoka\miniconda3\envs\nisar-era5\Lib\site-packages\pyproj\network.py:59: UserWarning: pyproj unable to set PROJ database path.
  _set_context_ca_bundle_path(ca_bundle_path)

## 1. Load station list

Only the names are needed here -- the coherence/closure-phase computation
reads everything else straight out of each station's saved `.nc` window
files.

In [2]:
# stations.geojson's AOI subfolder -- this example run uses Alaska.
stations_path = Path.cwd() / "ismn_data" / "alaska" / "stations.geojson"

with open(stations_path) as f:
    stations_geojson = json.load(f)

station_names = [feat["properties"]["station_val"] for feat in stations_geojson["features"]]

print(f"Loaded {len(station_names)} station names")
station_names

Loaded 20 station names

['MooseInc',
 'Aniak',
 'AtigunPass',
 'Coldfoot',
 'EagleSummit',
 'GobblersKnob',
 'GraniteCrk',
 'ImnaviatCreek',
 'LittleChenaRidge',
 'McGrath',
 'Nenana',
 'NukaGlacier',
 'PilgrimHotSprings',
 'PrudhoeBay',
 'RockyPoint',
 'SpringCreek',
 'SusitnaValleyHigh',
 'TurnagainPass',
 'UpperNomeCreek',
 'Kenai-29-ENE']

## 2. Process each station: group by track, compute coherence and closure phase, save CSVs

`process_station()` groups each station's saved windows by track, computes
HH/HV coherence and closure phase as described in the module note above,
and saves both CSVs under `output_dir`. A station with no saved window
files gets two empty (header-only) CSVs rather than an error.

In [3]:
COHERENCE_WINDOW_HALF = 1  # window half-size for coherence/closure phase estimation; 1 = 3x3 (default), 2 = 5x5, etc.
# Larger reduces the small-sample bias in the coherence estimate (worst at low true coherence with the 3x3 default)
# at the cost of spatial resolution around the station.

# Reads the real saved windows for this example run's AOI (Alaska).
gslc_dir = Path.cwd() / "nisar_data" / "alaska_GSLC_windows"
output_dir = Path.cwd() / "nisar_data" / "alaska_GSLC_coherence_closure"

for station_name in station_names:
    coherence_path, closure_path = process_station(
        station_name, gslc_dir, output_dir, window_half=COHERENCE_WINDOW_HALF
    )
    n_coherence = sum(1 for _ in open(coherence_path)) - 1
    n_closure = sum(1 for _ in open(closure_path)) - 1
    print(f"{station_name}: {n_coherence} pair(s) -> {coherence_path.name}, "
          f"{n_closure} triplet(s) -> {closure_path.name}")

MooseInc: 36 pair(s) -> MooseInc_NISAR_GSLC_coherence.csv, 34 triplet(s) -> MooseInc_NISAR_GSLC_closure_phase.csv
Aniak: 0 pair(s) -> Aniak_NISAR_GSLC_coherence.csv, 0 triplet(s) -> Aniak_NISAR_GSLC_closure_phase.csv

AtigunPass: 32 pair(s) -> AtigunPass_NISAR_GSLC_coherence.csv, 28 triplet(s) -> AtigunPass_NISAR_GSLC_closure_phase.csv

Coldfoot: 36 pair(s) -> Coldfoot_NISAR_GSLC_coherence.csv, 34 triplet(s) -> Coldfoot_NISAR_GSLC_closure_phase.csv

EagleSummit: 52 pair(s) -> EagleSummit_NISAR_GSLC_coherence.csv, 48 triplet(s) -> EagleSummit_NISAR_GSLC_closure_phase.csv

GobblersKnob: 36 pair(s) -> GobblersKnob_NISAR_GSLC_coherence.csv, 34 triplet(s) -> GobblersKnob_NISAR_GSLC_closure_phase.csv

GraniteCrk: 49 pair(s) -> GraniteCrk_NISAR_GSLC_coherence.csv, 45 triplet(s) -> GraniteCrk_NISAR_GSLC_closure_phase.csv

ImnaviatCreek: 28 pair(s) -> ImnaviatCreek_NISAR_GSLC_coherence.csv, 22 triplet(s) -> ImnaviatCreek_NISAR_GSLC_closure_phase.csv

LittleChenaRidge: 57 pair(s) -> LittleChenaRidge_NISAR_GSLC_coherence.csv, 58 triplet(s) -> LittleChenaRidge_NISAR_GSLC_closure_phase.csv

McGrath: 31 pair(s) -> McGrath_NISAR_GSLC_coherence.csv, 34 triplet(s) -> McGrath_NISAR_GSLC_closure_phase.csv
Nenana: 0 pair(s) -> Nenana_NISAR_GSLC_coherence.csv, 0 triplet(s) -> Nenana_NISAR_GSLC_closure_phase.csv

NukaGlacier: 52 pair(s) -> NukaGlacier_NISAR_GSLC_coherence.csv, 48 triplet(s) -> NukaGlacier_NISAR_GSLC_closure_phase.csv

PilgrimHotSprings: 65 pair(s) -> PilgrimHotSprings_NISAR_GSLC_coherence.csv, 70 triplet(s) -> PilgrimHotSprings_NISAR_GSLC_closure_phase.csv
PrudhoeBay: 0 pair(s) -> PrudhoeBay_NISAR_GSLC_coherence.csv, 0 triplet(s) -> PrudhoeBay_NISAR_GSLC_closure_phase.csv

RockyPoint: 41 pair(s) -> RockyPoint_NISAR_GSLC_coherence.csv, 44 triplet(s) -> RockyPoint_NISAR_GSLC_closure_phase.csv

SpringCreek: 34 pair(s) -> SpringCreek_NISAR_GSLC_coherence.csv, 26 triplet(s) -> SpringCreek_NISAR_GSLC_closure_phase.csv

SusitnaValleyHigh: 40 pair(s) -> SusitnaValleyHigh_NISAR_GSLC_coherence.csv, 30 triplet(s) -> SusitnaValleyHigh_NISAR_GSLC_closure_phase.csv

TurnagainPass: 38 pair(s) -> TurnagainPass_NISAR_GSLC_coherence.csv, 32 triplet(s) -> TurnagainPass_NISAR_GSLC_closure_phase.csv

UpperNomeCreek: 57 pair(s) -> UpperNomeCreek_NISAR_GSLC_coherence.csv, 58 triplet(s) -> UpperNomeCreek_NISAR_GSLC_closure_phase.csv

Kenai-29-ENE: 32 pair(s) -> Kenai-29-ENE_NISAR_GSLC_coherence.csv, 28 triplet(s) -> Kenai-29-ENE_NISAR_GSLC_closure_phase.csv

## 3. (Optional) Preview one station's output

In [4]:
import pandas as pd

preview_station = station_names[0]
coherence_df = pd.read_csv(output_dir / f"{preview_station}_NISAR_GSLC_coherence.csv")
closure_df = pd.read_csv(output_dir / f"{preview_station}_NISAR_GSLC_closure_phase.csv")

print(f"--- {preview_station} coherence (pairs) ---")
display(coherence_df)
print(f"\n--- {preview_station} closure phase (triplets) ---")
display(closure_df)

--- MooseInc coherence (pairs) ---

,date_1,date_2,temporal_baseline_days,orbit_dir,orbit_num,local_incidence_angle_deg,coherence_HH,phase_HH,coherence_HV,phase_HV
0,2026-06-27T05:52:57,2026-07-09T05:52:56,11.999988,Descending,15,45.806715,0.530313,0.740812,0.401262,2.174185
1,2026-06-27T05:52:57,2026-07-21T05:52:56,23.999988,Descending,15,45.806953,0.645623,-1.858867,0.798244,-2.206730
2,2026-06-27T05:52:57,2026-08-14T05:52:54,47.999965,Descending,15,45.809954,0.116891,-2.543220,0.269718,0.169968
3,2026-07-09T05:52:56,2026-07-21T05:52:56,12.000000,Descending,15,45.804586,0.560371,-1.779822,0.660659,1.997276
4,2026-07-09T05:52:56,2026-08-14T05:52:54,35.999977,Descending,15,45.807587,0.352010,-2.394195,0.402953,-2.226812
5,2026-07-21T05:52:56,2026-08-14T05:52:54,23.999977,Descending,15,45.807825,0.284550,-1.291278,0.133732,1.430785
6,2026-06-19T14:30:45,2026-07-01T14:30:44,11.999988,Ascending,78,37.931900,0.681133,0.327417,0.694660,-2.135794
7,2026-06-19T14:30:45,2026-07-13T14:30:44,23.999988,Ascending,78,37.931536,0.453750,1.892721,0.140997,1.002024
8,2026-06-19T14:30:45,2026-07-25T14:30:43,35.999977,Ascending,78,37.930729,0.171612,0.249114,0.150346,2.528446
9,2026-06-19T14:30:45,2026-08-18T14:30:42,59.999965,Ascending,78,37.928169,0.060724,-2.484441,0.212532,0.515429
10,2026-07-01T14:30:44,2026-07-13T14:30:44,12.000000,Ascending,78,37.934389,0.324555,2.431973,0.220750,-2.439034
11,2026-07-01T14:30:44,2026-07-25T14:30:43,23.999988,Ascending,78,37.933582,0.142823,-1.662686,0.456523,0.130703
12,2026-07-01T14:30:44,2026-08-18T14:30:42,47.999977,Ascending,78,37.931023,0.292553,-0.104646,0.147107,1.134850
13,2026-07-13T14:30:44,2026-07-25T14:30:43,11.999988,Ascending,78,37.933218,0.536790,-0.007963,0.222754,1.013777
14,2026-07-13T14:30:44,2026-08-18T14:30:42,35.999977,Ascending,78,37.930658,0.204406,-2.408759,0.435081,-1.082277
15,2026-07-25T14:30:43,2026-08-18T14:30:42,23.999988,Ascending,78,37.929852,0.609896,-2.148677,0.288202,-0.494170
16,2026-06-20T05:44:38,2026-07-02T05:44:37,11.999988,Descending,87,40.244844,0.490746,1.956848,0.711807,1.268230
17,2026-06-20T05:44:38,2026-07-14T05:44:37,23.999988,Descending,87,40.246449,0.715022,2.604041,0.800772,1.610930
18,2026-06-20T05:44:38,2026-07-26T05:44:36,35.999977,Descending,87,40.244318,0.635634,2.612274,0.549981,1.526124
19,2026-06-20T05:44:38,2026-08-19T05:44:35,59.999965,Descending,87,40.241217,0.684499,-1.758033,0.288956,0.328729
20,2026-07-02T05:44:37,2026-07-14T05:44:37,12.000000,Descending,87,40.249632,0.637512,0.550589,0.788600,0.449426
21,2026-07-02T05:44:37,2026-07-26T05:44:36,23.999988,Descending,87,40.247501,0.600953,0.824257,0.544218,-0.067449
22,2026-07-02T05:44:37,2026-08-19T05:44:35,47.999977,Descending,87,40.244400,0.529987,2.611080,0.560316,-1.138540
23,2026-07-14T05:44:37,2026-07-26T05:44:36,11.999988,Descending,87,40.249105,0.526627,-0.237974,0.468777,-0.292934
24,2026-07-14T05:44:37,2026-08-19T05:44:35,35.999977,Descending,87,40.246004,0.287005,1.599122,0.486750,-1.726109
25,2026-07-26T05:44:36,2026-08-19T05:44:35,23.999988,Descending,87,40.243874,0.742808,1.669878,0.666750,-0.590263
26,2026-06-24T14:22:26,2026-07-06T14:22:25,11.999988,Ascending,150,43.666729,0.471560,2.896692,0.635079,3.127776
27,2026-06-24T14:22:26,2026-07-18T14:22:21,23.999942,Ascending,150,43.668936,0.578732,-0.871987,0.579306,-1.130762
28,2026-06-24T14:22:26,2026-08-11T14:22:20,47.999931,Ascending,150,43.671017,0.658129,2.661064,0.326512,-0.309439
29,2026-06-24T14:22:26,2026-08-23T14:22:20,59.999931,Ascending,150,43.668846,0.256451,1.184645,0.357272,0.050279
30,2026-07-06T14:22:25,2026-07-18T14:22:21,11.999954,Ascending,150,43.666933,0.359864,1.676682,0.294734,1.904157
31,2026-07-06T14:22:25,2026-08-11T14:22:20,35.999942,Ascending,150,43.669014,0.614958,-0.110402,0.316566,2.498227
32,2026-07-06T14:22:25,2026-08-23T14:22:20,47.999942,Ascending,150,43.666843,0.281528,2.829494,0.249100,-1.745116
33,2026-07-18T14:22:21,2026-08-11T14:22:20,23.999988,Ascending,150,43.671221,0.437840,-2.022665,0.385791,-0.223659
34,2026-07-18T14:22:21,2026-08-23T14:22:20,35.999988,Ascending,150,43.669050,0.314319,-3.080685,0.487702,0.913449
35,2026-08-11T14:22:20,2026-08-23T14:22:20,12.000000,Ascending,150,43.671131,0.326545,-1.946208,0.379331,0.271497

--- MooseInc closure phase (triplets) ---

,date_1,date_2,date_3,temporal_baseline_12_days,temporal_baseline_23_days,temporal_baseline_13_days,orbit_dir,orbit_num,local_incidence_angle_deg,closure_phase_HH,closure_phase_HV,min_coherence_HH,min_coherence_HV
0,2026-06-27T05:52:57,2026-07-09T05:52:56,2026-07-21T05:52:56,11.999988,12.000000,23.999988,Descending,15,45.806085,0.819857,0.095006,0.530313,0.401262
1,2026-06-27T05:52:57,2026-07-09T05:52:56,2026-08-14T05:52:54,11.999988,35.999977,47.999965,Descending,15,45.808085,0.889837,-0.222595,0.116891,0.269718
2,2026-06-27T05:52:57,2026-07-21T05:52:56,2026-08-14T05:52:54,23.999988,23.999977,47.999965,Descending,15,45.808244,-0.606925,-0.945914,0.116891,0.133732
3,2026-07-09T05:52:56,2026-07-21T05:52:56,2026-08-14T05:52:54,12.000000,23.999977,35.999977,Descending,15,45.806666,-0.676905,-0.628313,0.284550,0.133732
4,2026-06-19T14:30:45,2026-07-01T14:30:44,2026-07-13T14:30:44,11.999988,12.000000,23.999988,Ascending,78,37.932608,0.866670,0.706333,0.324555,0.140997
5,2026-06-19T14:30:45,2026-07-01T14:30:44,2026-07-25T14:30:43,11.999988,23.999988,35.999977,Ascending,78,37.932070,-1.584383,1.749648,0.142823,0.150346
6,2026-06-19T14:30:45,2026-07-01T14:30:44,2026-08-18T14:30:42,11.999988,47.999977,59.999965,Ascending,78,37.930364,2.707212,-1.516374,0.060724,0.147107
7,2026-06-19T14:30:45,2026-07-13T14:30:44,2026-07-25T14:30:43,23.999988,11.999988,35.999977,Ascending,78,37.931828,1.635644,-0.512645,0.171612,0.140997
8,2026-06-19T14:30:45,2026-07-13T14:30:44,2026-08-18T14:30:42,23.999988,35.999977,59.999965,Ascending,78,37.930121,1.968403,-0.595683,0.060724,0.140997
9,2026-06-19T14:30:45,2026-07-25T14:30:43,2026-08-18T14:30:42,35.999977,23.999988,59.999965,Ascending,78,37.929583,0.584878,1.518847,0.060724,0.150346
10,2026-07-01T14:30:44,2026-07-13T14:30:44,2026-07-25T14:30:43,12.000000,11.999988,23.999988,Ascending,78,37.933730,-2.196489,-1.555961,0.142823,0.220750
11,2026-07-01T14:30:44,2026-07-13T14:30:44,2026-08-18T14:30:42,12.000000,35.999977,47.999977,Ascending,78,37.932023,0.127861,1.627024,0.204406,0.147107
12,2026-07-01T14:30:44,2026-07-25T14:30:43,2026-08-18T14:30:42,23.999988,23.999988,47.999977,Ascending,78,37.931485,2.576469,-1.498317,0.142823,0.147107
13,2026-07-13T14:30:44,2026-07-25T14:30:43,2026-08-18T14:30:42,11.999988,23.999988,35.999977,Ascending,78,37.931243,0.252119,1.601884,0.204406,0.222754
14,2026-06-20T05:44:38,2026-07-02T05:44:37,2026-07-14T05:44:37,11.999988,12.000000,23.999988,Descending,87,40.246975,-0.096604,0.106726,0.490746,0.711807
15,2026-06-20T05:44:38,2026-07-02T05:44:37,2026-07-26T05:44:36,11.999988,23.999988,35.999977,Descending,87,40.245555,0.168831,-0.325343,0.490746,0.544218
16,2026-06-20T05:44:38,2026-07-02T05:44:37,2026-08-19T05:44:35,11.999988,47.999977,59.999965,Descending,87,40.243487,0.042776,-0.199039,0.490746,0.288956
17,2026-06-20T05:44:38,2026-07-14T05:44:37,2026-07-26T05:44:36,23.999988,11.999988,35.999977,Descending,87,40.246624,-0.246207,-0.208128,0.526627,0.468777
18,2026-06-20T05:44:38,2026-07-14T05:44:37,2026-08-19T05:44:35,23.999988,35.999977,59.999965,Descending,87,40.244556,-0.321989,-0.443908,0.287005,0.288956
19,2026-06-20T05:44:38,2026-07-26T05:44:36,2026-08-19T05:44:35,35.999977,23.999988,59.999965,Descending,87,40.243136,-0.243000,0.607133,0.635634,0.288956
20,2026-07-02T05:44:37,2026-07-14T05:44:37,2026-07-26T05:44:36,12.000000,11.999988,23.999988,Descending,87,40.248746,-0.511642,0.223941,0.526627,0.468777
21,2026-07-02T05:44:37,2026-07-14T05:44:37,2026-08-19T05:44:35,12.000000,35.999977,47.999977,Descending,87,40.246679,-0.461369,-0.138143,0.287005,0.486750
22,2026-07-02T05:44:37,2026-07-26T05:44:36,2026-08-19T05:44:35,23.999988,23.999988,47.999977,Descending,87,40.245258,-0.116945,0.480829,0.529987,0.544218
23,2026-07-14T05:44:37,2026-07-26T05:44:36,2026-08-19T05:44:35,11.999988,23.999988,35.999977,Descending,87,40.246328,-0.167218,0.842912,0.287005,0.468777
24,2026-06-24T14:22:26,2026-07-06T14:22:25,2026-07-18T14:22:21,11.999988,11.999954,23.999942,Ascending,150,43.667533,-0.837824,-0.120491,0.359864,0.294734
25,2026-06-24T14:22:26,2026-07-06T14:22:25,2026-08-11T14:22:20,11.999988,35.999942,47.999931,Ascending,150,43.668920,0.125225,-0.347743,0.471560,0.316566
26,2026-06-24T14:22:26,2026-07-06T14:22:25,2026-08-23T14:22:20,11.999988,47.999942,59.999931,Ascending,150,43.667473,-1.741645,1.332381,0.256451,0.249100
27,2026-06-24T14:22:26,2026-07-18T14:22:21,2026-08-11T14:22:20,23.999942,23.999988,47.999931,Ascending,150,43.670391,0.727470,-1.044982,0.437840,0.326512
28,2026-06-24T14:22:26,2026-07-18T14:22:21,2026-08-23T14:22:20,23.999942,35.999988,59.999931,Ascending,150,43.668944,1.145868,-0.267592,0.256451,0.357272
29,2026-06-24T14:22:26,2026-08-11T14:22:20,2026-08-23T14:22:20,47.999931,12.000000,59.999931,Ascending,150,43.670331,-0.469789,-0.088221,0.256451,0.326512
30,2026-07-06T14:22:25,2026-07-18T14:22:21,2026-08-11T14:22:20,11.999954,23.999988,35.999942,Ascending,150,43.669056,-0.235580,-0.817729,0.359864,0.294734
31,2026-07-06T14:22:25,2026-07-18T14:22:21,2026-08-23T14:22:20,11.999954,35.999988,47.999942,Ascending,150,43.667609,2.049688,-1.720464,0.281528,0.249100
32,2026-07-06T14:22:25,2026-08-11T14:22:20,2026-08-23T14:22:20,35.999942,12.000000,47.999942,Ascending,150,43.668996,1.397080,-1.768345,0.281528,0.249100
33,2026-07-18T14:22:21,2026-08-11T14:22:20,2026-08-23T14:22:20,23.999988,12.000000,35.999988,Ascending,150,43.670467,-0.888188,-0.865610,0.314319,0.379331

<hr>

## Summary

You now have, under `nisar_data/<AOI>_GSLC_coherence_closure/`, two CSVs
per station: `{station}_NISAR_GSLC_coherence.csv` (every pair,
`coherence_HH`/`coherence_HV`) and `{station}_NISAR_GSLC_closure_phase.csv`
(every triplet, `closure_phase_HH`/`_HV` + `min_coherence_HH`/`_HV`) -- see
the module note above for the full column list.

Re-running after more GSLC windows are downloaded simply rebuilds both
CSVs from whatever `.nc` files currently exist -- safe to re-run any time.

<hr>